version: '3'

services:
  rundeck:
    container_name: rundeck
    image: rundeck/rundeck:SNAPSHOT
    hostname: rundeck
    environment:
      - RUNDECK_DATABASE_DRIVER
      - RUNDECK_DATABASE_USERNAME
      - RUNDECK_DATABASE_PASSWORD
      - RUNDECK_DATABASE_URL
      - RUNDECK_GRAILS_URL
    volumes:
      - ${RUNDECK_LICENSE_FILE:-/dev/null}:/home/rundeck/etc/rundeckpro-license.key
      - ./data/rundeck/projects/:/home/rundeck/projects/
      - ./data/rundeck/scripts:/home/rundeck/scripts/
      - ./data/rundeck/.ssh:/home/rundeck/.ssh/
    ports:
      - 7000:4440
    links:
      - mysql
      - command
    networks:
      rundeck_network:

  reverse_proxy_rundeck:
    container_name: reverse-proxy-rundeck
    image: nginx:1.18-alpine
    links:
      - rundeck_enterprise
    volumes:
      - ./context/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80

  mysql:
    container_name: mysql
    image: mysql:5.7
    expose:
      - 3306
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE
      - MYSQL_USER
      - MYSQL_PASSWORD
    volumes:
      - ./data/db:/var/lib/mysql
    networks:
      rundeck_network:

  command:
    container_name: command
    build:
      context: ../app/context/command
    volumes:
      - ../app/command:/usr/local/command
    ports:
      - 10022:22
    command: /bin/sh -c "sudo /etc/init.d/sshd restart && tail -f /dev/null"
    networks:
      rundeck_network:

  job:
    container_name: job
    build:
      context: ../app/context/command
    volumes:
      - ../app/command:/usr/local/command
    ports:
      - 10023:22
    command: /bin/sh -c "sudo /etc/init.d/sshd restart && tail -f /dev/null"
    networks:
      rundeck_network:

  worker:
    container_name: worker
    build:
      context: ../app/context/command
    volumes:
      - ../app/command:/usr/local/command
    ports:
      - 10024:22
    command: /bin/sh -c "sudo /etc/init.d/sshd restart && tail -f /dev/null"
    networks:
      rundeck_network:

networks:
  rundeck_network:
    name: rundeck-network
